// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkl5BwDAjEN3LJonn3fK1zFTePDcWCsc8',
    appId: '1:735213964913:web:5533a9471502f1e26ed5d0',
    messagingSenderId: '735213964913',
    projectId: 'sakny-c00c7',
    authDomain: 'sakny-c00c7.firebaseapp.com',
    storageBucket: 'sakny-c00c7.appspot.com',
    measurementId: 'G-MVKPMGJHY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGF1ly45x7UnElRhiBlceMMyMHRN0qqe8',
    appId: '1:735213964913:android:e9fb6557b4c145b66ed5d0',
    messagingSenderId: '735213964913',
    projectId: 'sakny-c00c7',
    storageBucket: 'sakny-c00c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3z0UUiUFEytOJPkRSjfEQaNXogWeBL6w',
    appId: '1:735213964913:ios:11fb04065eca74856ed5d0',
    messagingSenderId: '735213964913',
    projectId: 'sakny-c00c7',
    storageBucket: 'sakny-c00c7.appspot.com',
    androidClientId: '735213964913-0uqqseqacf2tlbofpjkbe7btvirb9s6v.apps.googleusercontent.com',
    iosClientId: '735213964913-91nejf772ru6pj9g73evt1rem2v9bhqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3z0UUiUFEytOJPkRSjfEQaNXogWeBL6w',
    appId: '1:735213964913:ios:11fb04065eca74856ed5d0',
    messagingSenderId: '735213964913',
    projectId: 'sakny-c00c7',
    storageBucket: 'sakny-c00c7.appspot.com',
    androidClientId: '735213964913-0uqqseqacf2tlbofpjkbe7btvirb9s6v.apps.googleusercontent.com',
    iosClientId: '735213964913-91nejf772ru6pj9g73evt1rem2v9bhqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkl5BwDAjEN3LJonn3fK1zFTePDcWCsc8',
    appId: '1:735213964913:web:0275867d977a76af6ed5d0',
    messagingSenderId: '735213964913',
    projectId: 'sakny-c00c7',
    authDomain: 'sakny-c00c7.firebaseapp.com',
    storageBucket: 'sakny-c00c7.appspot.com',
    measurementId: 'G-471C9MF4PT',
  );
}
